Add DFT-D3 as an external potential
eljost/pysisyphus pull request #244
Opened 2023-02-03 05:14 UTC by bapride11

Some programs available as a calculator don't have built-in D3/D3(BJ) dispersion corrections (e.g. OpenMolcas). As D3 is a density-independent, atom-pairwise correction that depends only on the molecular geometry, it effectively functions as an additive external potential. This pull request aims to add D3 as an available external potential (even if it leverages the Calculator class for I/O). As implemented, it is assumed that the dftd3 binary is available on $PATH, but the code is freely available under the GPL at https://www.chemie.uni-bonn.de/grimme/de/software/dft-d3/get_dft-d3.

2023-02-09 08:33 UTC, eljost requested changes

2023-02-09 08:33 UTC, eljost commented on pysisyphus/calculators/DFTD3.py
> +import os.path
Import is not needed

2023-02-09 08:33 UTC, eljost commented on pysisyphus/calculators/DFTD3.py
> +        grad = np.loadtxt(os.path.join(path,"dftd3_gradient"))
The `path` is actually a pathlib.Path and overloads the `/` operator to allow path concatenation.

So this line should be
`grad = np.loadtxt(path / "dftd3_gradient")`

2023-02-09 08:33 UTC, eljost commented on pysisyphus/calculators/DFTD3.py
> +        super(DFTD3, self).__init__(**kwargs)
This can just be `super().__init__(**kwargs)`

2023-02-09 08:33 UTC, eljost commented on pysisyphus/calculators/DFTD3.py
> +import os.path
Imports should be ordered like this

1. Modules from stdlib
2. Blank line
3. Third party packages, e.g., numpy
4. Blank line
5. Imports from own package, i.e., pysisyphus
6. Two blank lines

```python
import re

import numpy as np

from pysisyphus.calculators.Calculator import Calculator
```

2023-02-09 08:33 UTC, eljost commented
Thanks for the contribution! Please see my remarks. I'm sure, they are easily adressed.

All the best
Johannes

2023-02-09 18:58 UTC, bapride11 commented
Hello Johannes,

I've made the requested changes in the latest commit. Thank you for the improvements!

Greg

2023-02-10 08:33 UTC, eljost approved these changes

2023-02-10 08:34 UTC, merged